name: complain_me
description: A flutter Project For filing Complaints
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  rflutter_alert: ^2.0.4
  modal_progress_hud: ^0.1.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.5
  intl: ^0.17.0
  geolocator: ^8.0.3
  geocoding: ^2.0.1
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: GT Eesti
      fonts:
        - asset: fonts/GT-Eesti-Pro-Display-Regular.ttf

  assets:
    - images/
    - assets/map_style.txt



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
